[package]
name = "rust_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.26.0"
features = ["bundled"]

[dependencies]
rocket = "0.5.0-rc.1"